### ISSUE TITLE
docker-credential-pass password containing extra newline makes everything fail

### ISSUE THREAD

**Issue by nilehmann** [docker/docker-credential-helpers#111]
In this line https://github.com/docker/docker-credential-helpers/blob/master/pass/pass_linux.go#L41 the variable `stored` contains `"pass is initialized\n"` which makes `stored == password` false. Adding a new line at the end of `password` fixes the problem for me.

**Comment by nilehmann** [comment]
Actually, everything fails because of the extra newline. Changing this line https://github.com/docker/docker-credential-helpers/blob/master/pass/pass_linux.go#L95 by `return strings.Trim(string(result), "\n"), nil` made things work for me. Not sure what should be the proper fix.

I'm using `pass v1.7.2`

**Comment by teohhanhui** [comment]
Duplicate of #107?

**Comment by nilehmann** [comment]
@teohhanhui, yes, same issue

**Comment by vdemeester** [comment]
Then it is closeable :angel:
