### ISSUE TITLE
Pass will not store credentials properly

### ISSUE THREAD

**Issue by kenneym** [docker/docker-credential-helpers#113]
After adding a newline character to the pass_linux.go file under the declaration for "password" (See issue #107 and #111), My pass credential helper began to function without throwing errors, and I was able to successfully login; however, once I began to perform attempt actions such as push and pull, docker indicated that my login credentials could not be successfully retrieved. Anyone have a resolution on making sure pass stores credentials correctly/ making sure the credential helper can retrieve them?

Here is some output for reference:

```console
$ pass
Password Store
└── docker-credential-helpers

$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: mkenney1
Password: 
Login Succeeded

$ pass
Password Store
└── docker-credential-helpers
    └── aHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEv
        └── mkenney1

$ docker image push mkenney/nginx
The push refers to repository [docker.io/mkenney/nginx]
3ff93588120e: Preparing 
24ee0a3fd4b9: Preparing 
d626a8ad97a1: Preparing 
unauthorized: incorrect username or password

$ docker login
Authenticating with existing credentials...
Stored credentials invalid or expired
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (mkenney1): 
```

**Comment by thaJeztah** [comment]
I think this was fixed by https://github.com/docker/docker-credential-helpers/pull/108
