### ISSUE TITLE
Pass Init Error on Ubuntu 18.04 using gpg2 

### ISSUE THREAD

**Issue by programingnotes** [docker/docker-credential-helpers#126]
I have read [issue 102](https://github.com/docker/docker-credential-helpers/issues/102) but running into a problem when running `pass init {keyid}` when said `{keyid}` is for an imported key. 

So after importing public and private gpg keys, the following commands are run in order listed: 

1. Establish ultimate key trust: 
    - `gpg2 --edit-key {keyid} trust quit`

2. Initialize `pass` with imported keyid: 
    - ` pass init {keyid}`

3. Insert new password into store called `docker-credential-helpers/docker-pass-initialized-check`:  
    - `pass insert docker-credential-helpers/docker-pass-initialized-check`

4. Type in password when promoted by 3 above (no quotes): 
     - pass is initialized 

5. Decrypt and print password for`docker-credential-helpers/docker-pass-initialized-check`: 
    - `pass show docker-credential-helpers/docker-pass-initialized-check` 

### `gpg: decryption failed: No secret key`

**Comment by git-developer** [comment]
Did you solve the problem?
