### ISSUE TITLE
docker-credential-pass commits about 10 times every time I run a docker command

### ISSUE THREAD

**Issue by brandon-arnold** [docker/docker-credential-helpers#133]
Every time I perform a `docker-compose pull` on my project at work, a sequence of commits happens in my `~/.password-store`:

```
~ pass git log --oneline
f778ba4 (HEAD -> master) Remove docker-credential-helpers/docker-pass-initialized-check from store.
7e1c8c2 Add given password for docker-credential-helpers/docker-pass-initialized-check to store.
deeb9b6 Remove docker-credential-helpers/docker-pass-initialized-check from store.
a8241d5 Add given password for docker-credential-helpers/docker-pass-initialized-check to store.
5e52262 Remove docker-credential-helpers/docker-pass-initialized-check from store.
1d66adc Add given password for docker-credential-helpers/docker-pass-initialized-check to store.
577d311 Add given password for docker-credential-helpers/docker-pass-initialized-check to store.
...
```

It does authenticate correctly, however. But I am going to plan on a reset hard HEAD and dropping `docker-credential-pass` if this is intended functionality.

**Comment by brandon-arnold** [comment]
Just searched and noticed that one José Gaspar has [asked the same question to the `password-store` mailing list last month](https://lists.zx2c4.com/pipermail/password-store/2018-November/003469.html). I've just pulled the version on the AUR that seems to have been updated in October and the issue is still happening. My next option is to use the actual master branch version?

**Comment by brandon-arnold** [comment]
Thanks @joelnb. Great info. I am not in a great place to test this fix because I no longer have access to the docker hub team project I was using at the time (just took a new job 😆 ). I bet what you said was it, however, and will be heeding it next time I am configuring a docker authentication. Thanks again!

**Comment by captn3m0** [comment]
A new release for 0.6.1 would be appreciated, so this could be fixed for users relying on the binary downloads. (Going to try switching to `docker-credential-pass-git`, will report back in a few days)

**Comment by joelnb** [comment]
Yeah, agreed. I'm honestly not sure who has the power to do a release on this project so I'm not sure who we can tag to possibly speed things up.

**Comment by eyJhb** [comment]
@vdemeester can you increment the release, so at some point the different distros will catch up?

**Comment by thaJeztah** [comment]
v0.6.2 and v0.6.3 were tagged on this repo, and the vendored code in the docker cli was also updated to match v0.6.3 (in https://github.com/docker/cli/pull/1983)
