### ISSUE TITLE
Tag builds are failing in Travis, possible credentials issue

### ISSUE THREAD

**Issue by javabrett** [docker/docker-credential-helpers#141]
See https://travis-ci.org/docker/docker-credential-helpers/jobs/398229257#L710 .

Noticed when looking at #123 - presumably releases are currently being hand-rolled?

Do Travis secret creds need checking/updating?

**Comment by thaJeztah** [comment]
I think this was fixed by https://github.com/docker/docker-credential-helpers/pull/159
