### ISSUE TITLE
Releases page does not contain binaries for ppc64le

### ISSUE THREAD

**Issue by avmgithub** [docker/docker-credential-helpers#144]
Hi, I tested the "make deb" command using the master branch and it creates pass and secretservice deb packages fine using Linux Ubuntu on ppc64le system.   What would it take to have binaries for ppc64le be included in the community release page ?    Can the community use a shared CI build with ppc64le systems ?  Please let me know.

**Comment by avmgithub** [comment]
Hi all just trying to follow-up on this.  Just FYI ,  if you don't have ppc64le systems,  OSU has a shared CI environment that the community can be used to build packages for ppc64le. Here is the CI dashboard: https://powerci.osuosl.org/   and here is the link to apply for a dev environment and CI access: https://osuosl.org/services/powerdev/

**Comment by ghatwala** [comment]
Any updates on this @thaJeztah  ( relevant #165 )  , what would it take to release power binaries of "docker-credential-helpers" ? Any pointers to take this forward ?

**Comment by thaJeztah** [comment]
I don't think there's plans currently to add more platforms to the releases page, but you should be able to build from source on your platform

**Comment by thaJeztah** [comment]
Current releases now have other architectures included; https://github.com/docker/docker-credential-helpers/releases/tag/v0.7.0

Closing this ticket as resolved
