### ISSUE TITLE
pass variant macos support

### ISSUE THREAD

**Issue by glensc** [docker/docker-credential-helpers#146]
looks like it's assumed that [`pass`](https://www.passwordstore.org/) is to be used on Linux only.

however `pass` written in bash, a frontend to `gpg`, and therefore is portable and works fine on macos, there's even brew [formula](https://github.com/Homebrew/homebrew-core/blob/9b37cb405386ed11af4cb68130d56ceb5335d413/Formula/pass.rb) available.

however build system assumes it's for Linux:

```
==> make pass
Last 15 lines from /Users/glen/Library/Logs/Homebrew/docker-credential-helper/03.make:
2019-05-04 18:16:10 +0300

make
pass

mkdir -p bin
go build -o bin/docker-credential-pass pass/cmd/main_linux.go
pass/cmd/main_linux.go:5:2: build constraints exclude all Go files in /private/tmp/docker-credential-helper-20190504-69257-nmhjjp/docker-credential-helpers-0.6.2/src/github.com/docker/docker-credential-helpers/pass
make: *** [pass] Error 1

```

in source code there's only Linux source:
- https://github.com/docker/docker-credential-helpers/tree/v0.6.2/pass

should be trivial to port to other platforms (macOS i'm interested now)

**Comment by glensc** [comment]
note, this builds just fine:

```
==> cp pass/cmd/main_linux.go pass/cmd/main_darwin.go
==> cp pass/pass_linux.go pass/pass_darwin.go
==> go build -o bin/docker-credential-pass pass/cmd/main_darwin.go
```

**Comment by hutson** [comment]
Looks like @ellsclytn filed a pull request #169 to allow `pass` to build on MacOS.

I'm looking forward to this change making it easier for Homebrew/Linuxbrew users to use the Docker Credentials Helper `pass` package across platforms for greater credential security and consistency. (https://github.com/Homebrew/homebrew-core/issues/39517)
