### ISSUE TITLE
Power binaries as part of releases

### ISSUE THREAD

**Issue by ghatwala** [docker/docker-credential-helpers#165]
Hi all/ @guillaumerose ,

1) Is there any plan to add - "power/ppc64le" binaries as part of future releases of this repo ?
2) Travis jobs are enabled for power builds - https://github.com/docker/docker-credential-helpers/pull/160 . Any plans to ship binaries via this /other(jenkins) mechanism ?

**Comment by lsmcfadden** [comment]
Hi @ghatwala @guillaumerose, any update or forward progress?

**Comment by ghatwala** [comment]
Probably @guillaumerose  would be best person to update on this / relay this to someone who matters.

**Comment by thaJeztah** [comment]
Looks like a duplicate of https://github.com/docker/docker-credential-helpers/issues/144
