### ISSUE TITLE
Problem when cross-compiling on Linux for OSX

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [docker/docker-credential-helpers#176]
Hi.

We're using v0.6.3 of this package, and we run into the following problem when cross-compiling under Linux:

```
build my-binary: cannot find module for path github.com/docker/docker-credential-helpers/registryurl
```

The build commands we are using is
```
env GOOS=darwin GOARCH=amd64 go mod download
env GOOS=darwin GOARCH=amd64 go build -v -x  -o my-binary
```

I'm experiencing this problem with Go 1.12 on Ubuntu 18.04 as well as on Travis-CI using the following setup:

```
sudo: true
os: linux
language: go
go:
  - 1.12.x
env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
```

Building for Linux and Windows works fine. Building the library on osx works fine too. We do not import `github.com/docker/docker-credential-helpers/registryurl` at all.

My `handler_darwin.go` looks as follows:
```golang
package credentialmanager

import (
	"net/url"

	"github.com/docker/docker-credential-helpers/osxkeychain"
)

// SetCreds stores the credentials consisting of an endpoint and an api token in the keychain.
func SetCreds(endPoint url.URL, apiToken string) error {
	return setCreds(osxkeychain.Osxkeychain{}, endPoint, apiToken)
}

// GetCreds reads the credentials and returns an endpoint, the api token, or potentially an error.
func GetCreds() (url.URL, string, error) {
	return getCreds(osxkeychain.Osxkeychain{})
}

// SetInstallCreds sets the install credentials
func SetInstallCreds(creds string) error {
	return setInstallCreds(osxkeychain.Osxkeychain{}, creds)
}

// GetInstallCreds gets the install credentials
func GetInstallCreds() (string, error) {
	return getInstallCreds(osxkeychain.Osxkeychain{})
}
```

**Comment by jesselang** [comment]
I'm running into this trying to compile on Darwin. I think this only presents when Go modules are in use. I have a hunch that #168 would resolve this.

**Comment by christian-kreuzberger-dtx** [comment]
Any update on this? It's blocking us from cross-compiling our CLI for MacOS

**Comment by christian-kreuzberger-dtx** [comment]
After some troubleshooting I got a different error message:
```
go build github.com/docker/docker-credential-helpers/osxkeychain: build constraints exclude all Go files in /home/ckreuzberger/work/pkg/mod/github.com/docker/docker-credential-helpers@v0.6.3/osxkeychain
```

Looking at osxkeychain, it becomes clear why:
https://github.com/docker/docker-credential-helpers/blob/38bea2ce277ad0c9d2a6230692b0606ca5286526/osxkeychain/osxkeychain_darwin.go#L3-L10

It requires objective C and some headers from MacOS directly, and I guess they are only available on MacOS?
