### ISSUE TITLE
macOS credentials not found error apparently changed

### ISSUE THREAD

**Issue by felixfontein** [docker/docker-credential-helpers#177]
https://github.com/docker/docker-credential-helpers/blob/master/osxkeychain/osxkeychain_darwin.go contains the hardcoded string `The specified item could not be found in the keychain.` supposedly returned by `SecCopyErrorMessageString` (https://github.com/docker/docker-credential-helpers/blob/master/osxkeychain/osxkeychain_darwin.c#L7-L15) when an entry cannot be found in the keychain. Apparently that error message changed to `No stored credential for XXX`, according to the error messages reported in docker/docker-py#2482.

It would probably better to not rely on magic strings returned by `SecCopyErrorMessageString`, but instead (also) using the enum values (https://developer.apple.com/documentation/security/1542001-security_framework_result_codes?language=objc), probably this one: [errSecItemNotFound](https://developer.apple.com/documentation/security/1542001-security_framework_result_codes/errsecitemnotfound?language=objc).

**Comment by gitrobert42** [comment]
I am not optimistic we will get an update to the code anytime soon. This repo's last commit was 9 months ago. 

In the meantime, for sites that don't actually require a login, like docker.elastic.co, here's a super janky workaround:

1. Trick docker-credential-store into thinking it has credentials for a site by adding the site to the `auths` key in to ~/.docker/config.json like so:
```
{
  "credsStore" : "desktop",
  "stackOrchestrator" : "swarm",
  "experimental" : "disabled",
  "auths" : {
    "https://index.docker.io/v1/" : {

    }
    "https://docker.elastic.co/" : {
    }
  }
}
```
2. Add fake credentials 
`echo "{ 'ServerURL': 'https://docker.elastic.co/kibana', 'Username': 'a', 'Secret': 'a' }" | docker-credential-desktop store`
Or you can store it in  ~/.docker/plaintext-passwords.json directly. That file has the format: 
```
{
  "auths": {
    "https://docker.elastic.co/": {
      "auth": "YTph"
    }
  }
}
```

`YTph` is what you get when you run `echo -n 'a:a' | base64`

**Comment by crazy-max** [comment]
> Apparently that error message changed to `No stored credential for XXX`, according to the error messages reported in [docker/docker-py#2482](https://github.com/docker/docker-py/issues/2482).

This is not related to the `osxkeychain` store but the `plaintext` store used in `docker-credential-desktop` when no credential store is set in the docker config:

```go
return "", "", errors.New("No stored credential for " + serverURL)
```

So best guess for https://github.com/docker/docker-py/issues/2482#issue-541389969 is this user didn't set any `credsStore` in `~/.docker/config.json` and therefore it fallback to `plaintext` store.

Suggest to https://github.com/docker/docker-py maintainers to add a new error case for this store.

**Comment by crazy-max** [comment]
> This is not related to the `osxkeychain` store but the `plaintext` store used in `docker-credential-desktop` when no credential store is set in the docker config:
> 
> ```go
> return "", "", errors.New("No stored credential for " + serverURL)
> ```

I don't see this implementation anymore in current `docker-credential-desktop` code base. Looks like it has changed years ago and now directly pass through the underlying credential helper.
