### ISSUE TITLE
Docker's credential request prompt on OSX missing "Okay" button text and styling.

### ISSUE THREAD

**Issue by amingilani** [docker/docker-credential-helpers#179]
After installing Docker, I get the following prompt. It's missing some essential styling on "Okay" button, along with the the button's text. It gives it a major phishing attempt vibe.

<img width="555" alt="Screenshot 2020-04-09 at 10 46 42 AM" src="https://user-images.githubusercontent.com/1188552/78862108-fdf63e80-7a4f-11ea-9870-b4c9f75fee28.png">

**Comment by mat007** [comment]
Thanks for the report, please see https://github.com/moby/moby/issues/39648#issuecomment-518192195 for some explanation (short answer: it’s a bug in OSX).
