### ISSUE TITLE
Compatibility with future Go versions

### ISSUE THREAD

**Issue by Bo98** [docker/docker-credential-helpers#196]
Just a heads up that Go 1.17 (and the just-released 1.16 without first changing `GO111MODULE`) won't support builds that aren't in module-aware mode.

The master build should work but the last tag (v0.6.3) does not. Is it possible you can tag a new release for this?

https://blog.golang.org/go116-module-changes

**Comment by thaJeztah** [comment]
This should be fixed by https://github.com/docker/docker-credential-helpers/pull/168, and the v0.6.4 and v0.7.0 tags
