### ISSUE TITLE
Issue on Centos 7

### ISSUE THREAD

**Issue by ahmed-bacha** [docker/docker-credential-helpers#20]
Hi,

I've installed the Linux package (release section) to launch the credential-helpers with docker but i got this error.

```
[vagrant@localhost vagrant]$ docker login
Error spawning command line 'dbus-launch --autolaunch=064b75ad1c534c24889b78bb2f262e51 --binary-syntax --close-stderr': Child process exited with code 1
```

And when i launch the dbus command from terminal, I get :

```
[vagrant@localhost vagrant]$ dbus-launch --autolaunch=064b75ad1c534c24889b78bb2f262e51 --binary-syntax --close-stderr
Autolaunch error: X11 initialization failed.
```

Centos 7 
Docker 1.11.2
credential-helpers-secretservice

```
[vagrant@localhost vagrant]$ rpm -qa | grep dbus
python-slip-dbus-0.4.0-2.el7.noarch
dbus-1.6.12-13.el7.x86_64
dbus-glib-0.100-7.el7.x86_64
dbus-python-1.1.1-9.el7.x86_64
dbus-x11-1.6.12-13.el7.x86_64
dbus-libs-1.6.12-13.el7.x86_64
```

Thanks :)

**Comment by ahmed-bacha** [comment]
Can you help please @runcom ?

**Comment by runcom** [comment]
@ahmed-bacha the Linux credentials helper you're using is only meant to work with an X11 session, I suspect you're using it without any. The helper is meant for now to work with "desktops"  but I'm currently working a new helper which will be used in "servers" (as I think your centos is a server, at least without any session)

**Comment by ahmed-bacha** [comment]
I used a headless EL7 for testing and I understand now. 
Thanks for your clear answer :) .

**Comment by runcom** [comment]
reopening to track work for headless servers

**Comment by thaJeztah** [comment]
The secretservice credentials-helper unfortunately can't be used headless, but https://github.com/docker/docker-credential-helpers/pull/81 added a `pass` credentials-helper, which can be used as an alternative (but requires the `pass` utility to be installed as a backend.
