### ISSUE TITLE
Bad permissions in docker-credential-pass release asset

### ISSUE THREAD

**Issue by andyneff** [docker/docker-credential-helpers#210]
The permissions in the [pass download](https://github.com/docker/docker-credential-helpers/releases/download/v0.6.4/docker-credential-pass-v0.6.4-amd64.tar.gz) are bad/insecure 667 instead of the standard 755, resulting in errors by default, or requiring people to chmod just to make it work out of the box.

```
-rw-rw-rwx 0/0         2818053 2021-06-07 09:16 docker-credential-pass
```

The secretservice has it correct in its tarball:

```
-rwxr-xr-x ebriney/ebriney 2495464 2021-06-07 09:22 docker-credential-secretservice
```

**Comment by thaJeztah** [comment]
Starting with the 0.7 releases (https://github.com/docker/docker-credential-helpers/pull/237), the GitHub artifacts are no longer a tar archive, and the binaries themselves are uploaded, so this should likely no longer be an issue
