### ISSUE TITLE
docker-credential-wincred: executable file not found in %PATH%

### ISSUE THREAD

**Issue by marcosmoreno** [docker/docker-credential-helpers#24]
Hi,

I am using docker toolbox for windows. When I try docker-login, I receive the following message:

```
$ docker login
error getting credentials - err: exec: "docker-credential-wincred": executable file not found in %PATH%, out: ``
```

I downloaded the binary (0.2.0) for docker-credential-wincred, put docker-credential-wincred in $PATH, and actually I can call it from the bash shell:

```
$ docker-credential-wincred
Usage: C:\Programas\docker-credential-wincred\docker-credential-wincred <store|get|erase>
```

Does someone have an idea why docker-credential-wincred is not found in docker login? 

Thank you in advance and best regards,
Moreno.

**Comment by marcosmoreno** [comment]
As a workaround, I copied the json file from .docker folder(from my docker-machine). This does not have the wincred part. It is always asking for credentials for login, but I can login now. Feel free to close the issue if it is not relevant. I would like to that it works though :-).

**Comment by murraytodd** [comment]
I'm having the same problem. Brand new install of Docker Toolbox 1.12 onto Windows 10. 

Total blocker for me.

**Comment by fatelgit** [comment]
Had the same issue a few minutes ago. I just want to add a few more details. 
There is no need to edit PATH Variables when downloading to the "Docker Toolbox" folder. Just paste the binaries mentioned above where you have your docker files (docker-machine.ex etc).
The lines you have to delete from "config.json" should look similar to: 

```json
"auths": {
	"your.registry.domain": {}
}
"credsStore": "wincred"
```

Keep in mind to leave the outer brackets to prevent errors. 
Thanks for sharing this. Saved me some time!

**Comment by thanhnhan2tn** [comment]
+1
Im using Window 10, from `~/.docker/config.json`
I just remove the `"credsStore": "wincred"` and it work for me.

**Comment by goto-satoru** [comment]
thanks thanhnhan2tn !

**Comment by kodeplus81** [comment]
Thanks thanhnhan2tn too!

**Comment by yuliyanm** [comment]
Thanks, people saved my day!

**Comment by kennyaires** [comment]
Thnks! worked well for me.

**Comment by MJCD** [comment]
Has someone submitted a PR for this?

**Comment by svn1991** [comment]
thank you @thanhnhan2tn

**Comment by yassermog** [comment]
after I update to Mac OS 10.13.1 (17B48) this problem appears and It solved by removing "credsStore":
from
~/.docker/config.json

**Comment by telalwar** [comment]
@thanhnhan2tn Thank you. It worked for me. Do you any why it fails with credsStore": "wincred"?

**Comment by lucianobragaweb** [comment]
Thank You!!

**Comment by marcosmoreno** [comment]
I guess that, as there is a workaround and a closed ticket that took care of the issue, this issue can be closed.
Thank everybody for their kind comments!

**Comment by yuklia** [comment]
@thanhnhan2tn i still have the same error 
```
cat ~/.docker/config.json
{
  "auths" : {

  }
}
```

**Comment by dariusdevops** [comment]
@yuklia If you're using Mac, you need to lock and unlock your keychain access once in order to get it to work. 
I had the same issue as yours and my config.json file looked exactly like yours and got it fixed by locking and unlocking the keychain access. Here's how to do that => https://www.youtube.com/watch?v=-OH0e_e2kYo&vl=en

**Comment by MJCD** [comment]
Because docker is trash and totally undermines it's own purpose because it
uses a precarious linux vm which it attempts to orchestrate via "automagic"
on anything other than... linux...

2/10 would not recommend to friends.

- Michael

**Comment by ylhyh** [comment]
In the newer version of Windows docker, store credentials in ~/.docker/config.json with base64 format will gets a WARNING, lile below:
`WARNING! Your password will be stored unencrypted in C:\Users\Administrator\.docker\config.json.`

It's recommanded to credentials in Windows Credentials Manager: Control Panel -> User Accounts -> Manage your credentials -> Windows Credentials

So the default "credStore" is settings to "wincred" in the config.json file at ~/.docker/config.json, like this:
`{
	"auths": {
		"192.168.0.8:10000": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.06.0-ce (windows)"
	},
	"credsStore": "wincred"
}`

To use a credentials store, you need an external helper program to interact with a specific keychain or external store. Docker requires the helper program to be in the client’s host $PATH

So please download "docker-credential-wincred.exe" from [https://github.com/docker/docker-credential-helpers/releases](https://github.com/docker/docker-credential-helpers/releases) and put into your client's host $PATH.

The error mentioned in the thread will gone.

Details about external credentials store please refer to: [https://docs.docker.com/engine/reference/commandline/login/#credentials-store](https://docs.docker.com/engine/reference/commandline/login/#credentials-store)

**Comment by Mehul9891** [comment]
Thanks for the help below helped me.

> Im using Window 10, from ~/.docker/config.json
> I just remove the "credsStore": "wincred" and it work for me.

**Comment by hnasr** [comment]
Took me a while as I couldn't get ~/.docker/config.json to work on my windows 10, turns out it was in my user profile...
 
Just in case someone else ran into it people 

`%userprofile%\.docker\config.json `

I removed this line and it worked

![image](https://user-images.githubusercontent.com/3898305/44471912-c9ffa880-a5e1-11e8-943c-6725a45c0514.png)

**Comment by firepol** [comment]
You don't need to edit any file, the solution is actually to download wincred, from https://github.com/docker/docker-credential-helpers/releases and place it in the same directory as the docker exetutable. Or add its PATH in the PATH variable, as the error message states.

**Comment by MJCD** [comment]
The solution is to make the windows installer do this as part of it's
processes if it's required by the DEFAULT CONFIGURATION of X thing. It's
therefore a DIRECT requirement. This is not really debatable surely.

- Michael

**Comment by MJCD** [comment]
Alternatively; Change the default config for windows installs (obviously)

- Michael

**Comment by clayms** [comment]
On Windows 10 running `docker build -t imageName` command from the cmd or PowerShell works just fine.  However, using the Docker SDK for Python I get the same error referenced in this thread.

From python:
```
import docker
dockerclient = docker.from_env()
dockerclient.images.build(
    path="./",
    tag="imageName"
)
```

Gives the following error:

```
StoreError: Credentials store docker-credential-wincred exited with "A specified logon session does not exist. It may already have been terminated.".
```

I have downloaded and unzipped wincreds as @firepol  suggested from PowerShell with: 

```
cd "C:\Program Files\Docker\Docker"
wget https://github.com/docker/docker-credential-helpers/releases/download/v0.6.0/docker-credential-wincred-v0.6.0-amd64.zip -OutFile "docker-credential-wincred-v0.6.0-amd64.zip"
Expand-Archive -Path "docker-credential-wincred-v0.6.0-amd64.zip" -DestinationPath "C:\Program Files\Docker\Docker"
```

then restarted the Docker service from PowerShell with:
```
restart-service *docker*
```

I still get the same error.

I then deleted `, "credsStore":"wincred"` from the `"$env:userprofile\.docker\config.json"` file as suggested multiple times in this thread, so the file is now:
```
{
        "auths": {
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/18.09.1 (windows)"
        }
}
```

Then restarted the Docker service again.  
I still get the same error.

Any other suggestions?

**Comment by sakthikanth** [comment]
> +1
> Im using Window 10, from `~/.docker/config.json`
> I just remove the `"credsStore": "wincred"` and it work for me.

Thanks...working

**Comment by ma-siddiqui** [comment]
> +1
> Im using Window 10, from `~/.docker/config.json`
> I just remove the `"credsStore": "wincred"` and it work for me.

in my case it was ubuntu 18.04  and I removed credential store line

**Comment by omerisildak** [comment]
I have had the same problem at wsl2. I  have solved the problem with deleting inside of the ~/.docker/config.json
After the deletion, I have tried logged again and it worked.

I hope it would help someone :)

**Comment by hajnalmt** [comment]
On wsl2 this issue is still on but I didn't have "credsStore": "wincred" I had "credsStore": "desktop.exe", deleting it solved the issue.

**Comment by stan-shih** [comment]
Thanks for the help below helped me. The problem I encountered is as follows...

```bash
$ docker-compose up
[+] Running 0/0
 - web Pulling                                                                                                                                                                     0.0s 
 - db Pulling                                                                                                                                                                      0.0s 
error getting credentials - err: exec: "docker-credential-wincred": executable file not found in %PATH%, out: ``
```

> +1 Im using Window 10, from `~/.docker/config.json` I just remove the `"credsStore": "wincred"` and it work for me.

**Comment by FDiskas** [comment]
In my case it was marked as trojan by antivirus 
```
docker-credential-wincred.exe Infect of Trojan.Win64.Agent.BFM
```
so probably it was deleted
