### ISSUE TITLE
Download Assets missing file extension in version 0.7.0

### ISSUE THREAD

**Issue by kiaka010** [docker/docker-credential-helpers#242]
Hi,  It seems that the download paths in the releases are missing the .tar.gz extensions in the latest build (0.7.0) compared to 0.6.4
https://github.com/docker/docker-credential-helpers/releases/tag/v0.6.4
https://github.com/docker/docker-credential-helpers/releases/tag/v0.7.0

This is causing some issues with circleci builds that use the docker orb 
https://circleci.com/developer/orbs/orb/circleci/docker#commands-install-docker-credential-helper
```        DOWNLOAD_URL="https://github.com/docker/docker-credential-helpers/releases/download/${RELEASE_VERSION}/${HELPER_FILENAME}-${RELEASE_VERSION}-amd64.tar.gz"```

**Comment by crazy-max** [comment]
@kiaka010 Do you have a link to the thread? Thanks.

**Comment by kiaka010** [comment]
https://github.com/CircleCI-Public/docker-orb/issues/154
