### ISSUE TITLE
Format of release

### ISSUE THREAD

**Issue by drgeb** [docker/docker-credential-helpers#255]
In previous version 0.64 for example the release artifacts were in the form .tar.gz. Seems like the naming convention changed and the .tar.gz is dropped

https://github.com/docker/docker-credential-helpers/releases/download/v0.6.4/docker-credential-pass-v0.6.4-amd64.tar.gz 

became now
https://github.com/docker/docker-credential-helpers/releases/download/v0.7.0/docker-credential-pass-v0.7.0.linux-amd64 

can we add the file extension to this  or go back to previous format ?

Thanks

**Comment by ningziwen** [comment]
+1 How could we install credential helper with current format? `tar xf` seems not working now.

**Comment by crazy-max** [comment]
https://github.com/docker/docker-credential-helpers/issues/242#issuecomment-1255132313
