### ISSUE TITLE
Please use annotated tags

### ISSUE THREAD

**Issue by fsateler** [docker/docker-credential-helpers#31]
The current release tags are not annotated, and thus breaks `git describe`:

```shell
git describe 
fatal: No annotated tags can describe 'f72c04f1d8e71959a6d103f808c50ccbad79b9fd'.
However, there were unannotated tags: try --tags.
```

To annotate them it is sufficient to add a message `-m "Release vX.Y.Z"`.

**Comment by JonathonReinhart** [comment]
The vast majority of projects I encounter don't use annotated tags. I think it's far easier to get used to using `git describe --tags`.
