### ISSUE TITLE
Using Config.json for TLS Authentication ?

### ISSUE THREAD

**Issue by jamroks** [docker/docker-credential-helpers#33]
Hi,

I was wondering if there is the possibility to use /home/user/.docker/config.json file to configure the tls authentication to a remote docker engine ( running in swarm mode).

Right now if we type docker help, we get this list of option ( on MacOS )

    --config string      Location of client config files (default "/Users/yourname/.docker")
-D, --debug Enable debug mode
-H, --host list Daemon socket(s) to connect to (default [])
-l, --log-level string Set the logging level ("debug", "info", "warn", "error", "fatal") (default "info")
--tls Use TLS; implied by --tlsverify
--tlscacert string Trust certs signed only by this CA (default "/Users/yourname/.docker/ca.pem")
--tlscert string Path to TLS certificate file (default "/Users/yourname/.docker/cert.pem")
--tlskey string Path to TLS key file (default "/Users/yourname/.docker/key.pem")
--tlsverify

The idea is to have those tls option ( --tls, --tlscacert, --tlscert, --tlskey, --tlsverify ) being configured inside the config.json file for convenience. i am well ware of other option like using passing tlsverify on every call :

docker --tlsverify ..etc
or using environment variable on every shell

export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH=~/.docker/zone1/
But i would like to know if the third option of using config.json to specify all TLS information would be possible now or in the future. i find it very elegant and convenient to have such info in a config file, just like the kubernetes community has with the kubeconfig file which is yaml file containing all the authentication info to a "kubernetes deployments" which is roughly equivalent to a swarm stack ( deployment) based on a docker-compose.yml (Version 3 format) of my micro service application.

it would look like this :

{
         "HttpHeaders": {
                  "MyHeader": "MyValue"
                },

         "StackContext": {
               "myStack1": {
                      "User": "UserProd",
                      "tlsverify": "true",
                      "tlscacert": "/Users/yourname/.docker/ca.pem",
                      "tlscert": "/Users/yourname/.docker/cert.pem",
                      "tlskey": "/Users/yourname/.docker/key.pem"
               },
               "myStack2": {
                     "User": "UserStaging",
                      "tlsverify": "true",
                      "tlscacert": "/Users/yourname/.docker/ca.pem",
                      "tlscert": "/Users/yourname/.docker/cert.pem",
                      "tlskey": "/Users/yourname/.docker/key.pem"
                }
          },

          "psFormat": "table {{.ID}}\\t{{.Image}}\\t{{.Command}}\\t{{.Labels}}",
    
	      "auths": {
		          "https://index.docker.io/v1/": {
			               "auth": "khsfdfhsjdskhlfhdlfjfjdj="
		          },
		          "https://registry-1.docker.io/v2/": {
			               "auth": "qlfldhflqshmfdhsdnferi="
		          }
	       }
}

**Comment by johnflavin** [comment]
I am not sure how you want this to work. Here are the options that I think you might mean:
1. Docker can write all this information to the config file, and exposes an API to do so, and `docker-client` can be updated to use that API. 
2. You write this information into the config file by hand, and (again) `docker-client` can be updated to read it and use it on your calls to docker. 
3. `docker-client` can be updated to manage all the preferences in the config file, which `docker-client` also reads out and uses on your calls to docker.

The only option I think would be doable is 1. The other two involve adding too many features to `docker-client` that aren't present in or documented by docker's API. Managing the contents of docker's config file is docker's responsibility. (And writing and managing our own config file seems like a nightmare.) 

The purpose of `docker-client` is to be a thin java wrapper around the docker API. As far as I'm aware (which, admittedly, is not very far) there is no docker API to manage these preferences. If that is not correct (again, totally possible that it is not correct), then send a link to their API docs about it, and we can work on getting a PR started. But if I'm correct and there is no API for this, I would characterize this as an "upstream" issue. If you request this feature from [docker/docker](http://github.com/docker/docker), they add it, they document it, and they expose it in their API, then we can add it here.

**Comment by vdemeester** [comment]
@jamroks I'm not sure this is the right repository to report as it seems to be a `docker` command line issue / proposal.

**Comment by thaJeztah** [comment]
Closing, as this looks to be something for https://github.com/docker/cli
