### ISSUE TITLE
I am trying to build under windows, using go 32 bit

### ISSUE THREAD

**Issue by asierra01** [docker/docker-credential-helpers#34]
c:\scripts\go\src\github.com\docker\docker-credential-helpers>make wincred
mkdir -p bin
go build -o bin/docker-credential-wincred wincred/cmd/main_windows.go
  %#    github.com/docker/docker-credential-helpers/vendor/github.com/danieljoos/wincred
vendor\github.com\danieljoos\wincred\native.go:124: type [1073741824]uintptr larger than address space
vendor\github.com\danieljoos\wincred\native.go:124: type [1073741824]uintptr too large
make: *** [wincred] Error 2
...I get this error

**Comment by thaJeztah** [comment]
https://github.com/docker/docker-credential-helpers/pull/168 updated this dependency, and that specific file is no longer in our code-base. I'm not sure if that fixes the issue, but let us know if you're still having issues compiling a current version of this repository.
