### ISSUE TITLE
docker-credential-osxkeychain asking for access to keychains and passwords it has no need for

### ISSUE THREAD

**Issue by mightyroser** [docker/docker-credential-helpers#47]
When I perform a docker build of a very simple docker file, docker-credential-osxkeychain prompts
me for access to my bitbucket.org password stored in my keychain.  There is absolutely no reason why
docker would need access to this password.

xxx@yyy ~/docker_test [0]$ docker --version
Docker version 17.03.0-ce, build 60ccb22
xxx@yyy ~/docker_test [0]$ vi Dockerfile
xxx@yyy ~/docker_test [0]$ cat Dockerfile 
FROM python:3.5-alpine
xxx@yyy ~/docker_test [0]$ docker build -t docker_build_creds_test .
Sending build context to Docker daemon 2.048 kB
Step 1/1 : FROM python:3.5-alpine
 ---> e3c9c70fb387
Successfully built e3c9c70fb387
xxx@yyy ~/docker_test [0]$ 

<img width="437" alt="screen shot 2017-03-08 at 10 26 38 am" src="https://cloud.githubusercontent.com/assets/25228271/23710219/f88520c2-03e9-11e7-9631-842fcd3189ce.png">

**Comment by vdemeester** [comment]
@mightyroser thanks for the report, this is tracked [here](https://github.com/docker/docker/issues/31517) and [here](https://github.com/docker/docker-credential-helpers/issues/46) 👼

**Comment by vdemeester** [comment]
This should be fixed with #49 merged and `v0.5.0` release. Will be closed once docker4mac update is there 👼

**Comment by n4ss** [comment]
This is fixed as of v0.5.0
