### ISSUE TITLE
osxkeychain includes "http:///" instead of "http://"

### ISSUE THREAD

**Issue by smccarthy** [docker/docker-credential-helpers#58]
I did a `docker login docker.artifactory.domain.net` and provided the username and password. I also tried `docker login http://docker.artifactory.domain.net` and it still didn't work correctly. The osxkeychain for Docker Credentials has the url as "http:///docker.artifactory.domain.net" instead of "http://docker.artifactory.domain.net"

This causes issues with doing a docker build . However docker pull for the same image works.

**Comment by n4ss** [comment]
Hi!
This issue is a duplicate of https://github.com/docker/docker-credential-helpers/issues/14

**Comment by smccarthy** [comment]
Thanks. Closing mine.
