### ISSUE TITLE
secretservice: requires X, cannot cross-compile

### ISSUE THREAD

**Issue by promiseofcake** [docker/docker-credential-helpers#78]
Looking to use this in conjunction with: https://github.com/bazelbuild/rules_docker.

I attempted to cross-compile `secretservice` w/ CGO on OSX but ran into some issues with `clang`. I decided to just build in a vbox instance to try to get around that and discovered that it seems like `libsecret-1` requires X11 to run? What would be the best way to attempt to use a credential helper in a non-gui environment (CI) in order to auth w/ external docker registries in order to push/pull images?

Or is that outside the scope of this repo?

Thanks!

**Comment by tych0** [comment]
Hi,

We've just merged a pass backend, which it looks like is available via homebrew: http://brewformulas.org/Pass which may be more useful.

**Comment by promiseofcake** [comment]
Awesome, will give it a go but I think that's all we need. Thank you!
