### ISSUE TITLE
Allow pass backend for Darwin hosts

### ISSUE THREAD

**Issue by promiseofcake** [docker/docker-credential-helpers#93]
Since `pass` can be installed on a variety of hosts, it would be nice if we could permit using it on Darwin machines as well. This would help bring parity between Linux CI environments and Linux production machines, etc.

I will work on a PR but do you see anything blocking this?

**Comment by promiseofcake** [comment]
Also -- are we testing `pass` in CI? I haven't been able to see that in a Travis build.

**Comment by n4ss** [comment]
I don't see an issue for this as long as you have to opt-out of the keychain-helper which is by far the safest cred storing mechanism on macOS.

**Comment by promiseofcake** [comment]
Turns out that we don't need the pass backend for our nix ci env, we were able to get it to work using the default docker-flat-storage which is good enough for us.
