### ISSUE TITLE
The pass command is already taken

### ISSUE THREAD

**Issue by nim-nim** [docker/docker-credential-helpers#98]
This project generates a pass command but it is already used by the http://zx2c4.com/projects/password-store/ which is packaged in major Linux distributions

**Comment by onlyjob** [comment]
Moreover, `pass` utility (from the "pass" package) is installed automatically on Debian when user installs any graphical desktop environment.

**Comment by vdemeester** [comment]
@nim-nim @onlyjob not sure I understand this issue. `docker-credential-helpers` doesn't *generate* a `pass` command. It will use it *by default*, if the command is present. The command generated by the project should be `bin/docker-credential-pass`, not `pass`

**Comment by onlyjob** [comment]
I see, probably not a problem then. I was investigating why GPG-agent password prompt appears on every invocation of `docker` command (even with `docker info`) and this seems relevant...

**Comment by vdemeester** [comment]
@onlyjob yeah, the relevant issue is https://github.com/docker/docker-credential-helpers/issues/96 then :wink: I got recently hit by that too, gonna try to fix it :angel: :wink:

**Comment by onlyjob** [comment]
Thank you.

**Comment by vdemeester** [comment]
@onlyjob I'm gonna close this one then :angel:
