### ISSUE TITLE
No pass init as required by tests

### ISSUE THREAD

**Issue by nim-nim** [docker/docker-credential-helpers#99]
ci/before_script_linux.sh instructs to run
pass init $key
before tests, but pass 0.6.0 replies
pass init 112D2F40
Usage: pass <store|get|erase|list|version>

**Comment by thaJeztah** [comment]
I think this was rewritten in https://github.com/docker/docker-credential-helpers/pull/231, so let me close, but feel free to comment if there's something remaining
